### PR TITLE
Corrected field name

### PR DESCRIPTION
**Pull request by kmalempa**
- To drop a packet egress_spec has to be set to 511

### CODE REVIEW

**Comment by antoninbas** [comment]
Thanks for your pull request. We can only accept contributions from p4.org members. Are you or your employer part of p4.org? You can join as an individual contributor by signing the Apache CLA. Send an email to membership@p4.org if you need to sign the CLA.

**Comment by kmalempa** [comment]
Hi ,

I would like to join as an individual contributor.

Thanks,
Kotesh

**Comment by kmalempa** [comment]
Hi Antonin,

Please find the attachments. Thank you for the help.

Thanks,
Kotesh

From: "Kotesh Malempati (kmalempa)" <kmalempa@cisco.com>
Date: Friday, 10 March 2017 at 1:11 PM
To: "membership@p4.org" <membership@p4.org>
Cc: Author <author@noreply.github.com>, p4lang/behavioral-model <reply@reply.github.com>, p4lang/behavioral-model <behavioral-model@noreply.github.com>
Subject: Re: [p4lang/behavioral-model] Corrected field name (#309)

Hi ,

I would like to join as an individual contributor.

Thanks,
Kotesh

**Comment by kmalempa** [comment]
Do I have to provide any thing else ?

**Comment by antoninbas** [comment]
I haven't heard back from p4.org. You may want to re-send your email to membership@p4.org and CC me (antonin@barefootnetworks.com) so I can follow-up with them as well.

**Pull request merged**
