### PR TITLE
fix tools for macOS

### PR DESCRIPTION
**Pull request by qin-nz**

### CODE REVIEW

**Comment by qin-nz** [comment]
@cc10512 Can you review my changes?

**Comment by qin-nz** [comment]
clang will throw a warning about `-pthread`
```
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
```

`-Werror` can stop build.
Remove it foc macOS may not be a good idea, but I can't find a better solution.

**Comment by qin-nz** [comment]
@hanw 
```
➞  g++ -v                                                                                                                                                                                                                                  
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I try to clean bmv2 and rebuild it and still has error.
```
clang: error: argument unused during compilation: '-pthread' [-Werror,-Wunused-command-line-argument]
```

**Comment by antoninbas** [comment]
@hanw @cc10512 do these changes make sense to you?

**Comment by hanw** [comment]
By looking at the documentation to install scapy on mac os, http://scapy.readthedocs.io/en/latest/installation.html, the changes in this PR makes sense to me. I am not sure why homebrew decided `brew install scapy` is not good enough.

**Comment by qin-nz** [comment]
@cc10512 
I just want to install scapy.
`brew install homebrew/python/scapy ` is broken and as @hanw  mention, this is official recommend way to install scapy.

**Comment by cc10512** [comment]
I see. Hmm, the joys of open-source software. I'm still not too happy pointing to that .rb file. It would make me much happier if you make a copy of it in tools/macos/brews and install it from there. Sounds good?

**Comment by qin-nz** [comment]
@cc10512 @hanw 
It my fault.
In the documentation, install scapy 2.x just need `pip` instead of `brew`.

However, pip is not include in macos by default. And it must use privileged account to install which may need user to enter password during running scripts.
So I didn't install pip before use it.

**Comment by antoninbas** [comment]
@qin-nz Now that @cc10512 has approved the PR I feel comfortable merging it. However you will need to fix the conflicts with the master branch first (I am not sure how you managed to have conflicts TBH if you only modified the macos bootsrap script). Please rebase your branch on top of master and squash all your commits into one.

**Comment by qin-nz** [comment]
@antoninbas Done!

I was modify `README.md` and then revert it and this lead to a conflict.

**Pull request merged**
