### PR TITLE
Fixes warning comparing integers of different signs

### PR DESCRIPTION
**Pull request by grodtron**
Changes the type of a variable storing a return code from
Judy1FreeArray from the unsigned type `Word_t` to `int`.

This variable was unused, but the unsigned type was causing a
warning with my compiler settings

### CODE REVIEW

**Comment by antoninbas** [comment]
which compiler settings gave you this warning, so I can reproduce it? (according to the Judy doc, I believe this is supposed to be unsigned).
also, did you or your employer (i.e. is your employer a P4.org member) sign the Apache CLA? Otherwise, I cannot accept your contribution.

**Comment by grodtron** [comment]
The error can be reproduced with the following command (from inside modules/bm_sim):

    clang++ -DHAVE_CONFIG_H -I. -I../.. -DBMELOG_ON -I../../modules/bf_lpm_trie/include -isystem../../third_party/jsoncpp/include -isystem../../third_party/spdlog/include -I../../modules/BMI/include -I./include/ -Wall -Werror -Wextra -stdlib=libstdc++ -std=c++11 -MT src/ageing.lo -MD -MP -MF src/.deps/ageing.Tpo -c src/ageing.cpp  -fPIC -DPIC -o src/.libs/ageing.o

The full error produced is:

    In file included from src/ageing.cpp:23:
    In file included from ./include/bm_sim/ageing.h:32:
    In file included from ./include/bm_sim/match_tables.h:29:
    In file included from ./include/bm_sim/match_units.h:38:
    ./include/bm_sim/handle_mgr.h:153:5: error: comparison of integers of different signs: 'Word_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
        J1FA(bytes_freed, handles);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/include/Judy.h:550:9: note: expanded from macro 'J1FA'
            J_0I(Rc, (&(PArray)), Judy1FreeArray, "Judy1FreeArray")
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/include/Judy.h:448:49: note: expanded from macro 'J_0I'
                if (((Rc) = Func(PArray, &J_Error)) == JERR)                \
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^  ~~~~
    In file included from src/ageing.cpp:23:
    In file included from ./include/bm_sim/ageing.h:32:
    In file included from ./include/bm_sim/match_tables.h:29:
    In file included from ./include/bm_sim/match_units.h:38:
    ./include/bm_sim/handle_mgr.h:214:5: error: comparison of integers of different signs: 'Word_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
        J1FA(Rc_word, handles);
        ^~~~~~~~~~~~~~~~~~~~~~
    /usr/include/Judy.h:550:9: note: expanded from macro 'J1FA'
            J_0I(Rc, (&(PArray)), Judy1FreeArray, "Judy1FreeArray")
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/include/Judy.h:448:49: note: expanded from macro 'J_0I'
                if (((Rc) = Func(PArray, &J_Error)) == JERR)                \
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^  ~~~~
    In file included from src/ageing.cpp:23:
    In file included from ./include/bm_sim/ageing.h:32:
    In file included from ./include/bm_sim/match_tables.h:31:
    ./include/bm_sim/ras.h:138:5: error: comparison of integers of different signs: 'Word_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
        J1FA(bytes_freed, members);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/include/Judy.h:550:9: note: expanded from macro 'J1FA'
            J_0I(Rc, (&(PArray)), Judy1FreeArray, "Judy1FreeArray")
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/include/Judy.h:448:49: note: expanded from macro 'J_0I'
                if (((Rc) = Func(PArray, &J_Error)) == JERR)                \
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^  ~~~~
    3 errors generated.

Regarding the Apache CLA I will have to speak with my employer, I am not sure if he has signed it, but he has given me permission to contribute so I'm sure it will not be an issue. I will get back to you on that shortly.

**Comment by antoninbas** [comment]
You can obtain the CLA by sending an email to prem "at" barefootnetworks.com

**Comment by antoninbas** [comment]
Hi Gordon,

I updated the whole repo to support clang++; there were a couple other issues in other files. This was done in #79 
I also added a clang++-3.6 build to the Travis regression.
Thanks for raising this issue.

**Comment by grodtron** [comment]
Great, thank you very much, it's a big help to us also!

**Pull request closed without merging**
