### PR TITLE
[psa_switch] Pre-allocate buffer in PSAHash extern implementation

### PR DESCRIPTION
**Pull request by antoninbas**

### CODE REVIEW

**Comment by antoninbas** [comment]
@DusanKrdzic this is passing all your unit tests. Do you see any issue with this?

**Comment by DusanKrdzic** [comment]
> @DusanKrdzic this is passing all your unit tests. Do you see any issue with this?

I am not sure what is the problem here.

**Comment by antoninbas** [comment]
My initial code sample (https://github.com/p4lang/behavioral-model/pull/1033#discussion_r704729881) had a few issues with it, so maybe that's why it didn't work for you originally. In particular `ptr` update was incorrect.

**Comment by DusanKrdzic** [comment]
> My initial code sample (https://github.com/p4lang/behavioral-model/pull/1033#discussion_r704729881) had a few issues with it, so maybe that's why it didn't work for you originally. In particular `ptr` update was incorrect.

Is now everything ok?

**Comment by antoninbas** [comment]
All your unit tests are passing. So if you can confirm that there is enough coverage in your unit tests, then I would say yes everything is ok and it can be merged.

**Comment by DusanKrdzic** [comment]
> All your unit tests are passing. So if you can confirm that there is enough coverage in your unit tests, then I would say yes everything is ok and it can be merged.

Yes, I can confirm that.

**Pull request merged**
