### PR TITLE
Update Dockerfile.grpc to use the correct branch in the PI repository [master -> main] 

### PR DESCRIPTION
**Pull request by Mtze**
Update the PI branch-name from master to main.

### CODE REVIEW

**Comment by Mtze** [comment]
The docker build still fails. I'll try to fix that, but I'm quite new to the topic so no guarantees 😬

**Comment by Mtze** [comment]
OMG - I was holding it wrong - Just saw the CI passed, so this should be good to go. Sorry for the confusion.

**Review by antoninbas — APPROVED** [review]
LGTM (but note that this is not verified by CI)
It's possible that there are some other issues with the Dockerfile, unless you were able to use it successfully on your machine?

**Comment by Mtze** [comment]
Ohh - Makes sense the CI should have detected the initial error it it would check the Docker build. Ups. 

I tried, but haven't found a solution. I tried different ubuntu base images but each ubuntu version generates different errors. I also had a look at the other docker files in the repositories, but unfortunately these are vastly different (different base images). I tried to understand the problem but unfortunately couldn't. Here are the last few lines of the docker build 

```
#20 157.2 Making all in server
#20 157.2 make[4]: Entering directory '/PI/proto/server'
#20 157.2 depbase=`echo gnmi_dummy.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
#20 157.2 /bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -I../frontend -isystem ../cpp_out -isystem ../grpc_out   -Wall -Werror -O0 -std=c++11 -MT gnmi_dummy.lo -MD -MP -MF $depbase.Tpo -c -o gnmi_dummy.lo gnmi_dummy.cpp &&\
#20 157.2 mv -f $depbase.Tpo $depbase.Plo
#20 157.2 depbase=`echo pi_server.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
#20 157.2 /bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -I../frontend -isystem ../cpp_out -isystem ../grpc_out   -Wall -Werror -O0 -std=c++11 -MT pi_server.lo -MD -MP -MF $depbase.Tpo -c -o pi_server.lo pi_server.cpp &&\
#20 157.2 mv -f $depbase.Tpo $depbase.Plo
#20 157.3 libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I../frontend -isystem ../cpp_out -isystem ../grpc_out -Wall -Werror -O0 -std=c++11 -MT pi_server.lo -MD -MP -MF .deps/pi_server.Tpo -c pi_server.cpp  -fPIC -DPIC -o .libs/pi_server.o
#20 157.3 libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I../frontend -isystem ../cpp_out -isystem ../grpc_out -Wall -Werror -O0 -std=c++11 -MT gnmi_dummy.lo -MD -MP -MF .deps/gnmi_dummy.Tpo -c gnmi_dummy.cpp  -fPIC -DPIC -o .libs/gnmi_dummy.o
#20 157.3 gnmi_dummy.cpp:21:27: fatal error: grpcpp/grpcpp.h: No such file or directory
#20 157.3 compilation terminated.
#20 157.3 make[4]: *** [gnmi_dummy.lo] Error 1
#20 157.3 make[4]: *** Waiting for unfinished jobs....
#20 157.3 Makefile:509: recipe for target 'gnmi_dummy.lo' failed
#20 157.4 pi_server.cpp:23:27: fatal error: grpcpp/grpcpp.h: No such file or directory
#20 157.4 compilation terminated.
#20 157.5 make[4]: *** [pi_server.lo] Error 1
#20 157.5 Makefile:509: recipe for target 'pi_server.lo' failed
#20 157.5 make[4]: Leaving directory '/PI/proto/server'
#20 157.5 make[3]: *** [all-recursive] Error 1
#20 157.5 Makefile:1717: recipe for target 'all-recursive' failed
#20 157.5 make[3]: Leaving directory '/PI/proto'
#20 157.5 Makefile:713: recipe for target 'all' failed
#20 157.5 make[2]: *** [all] Error 2
#20 157.5 make[2]: Leaving directory '/PI/proto'
#20 157.5 make[1]: *** [all-recursive] Error 1
#20 157.5 Makefile:452: recipe for target 'all-recursive' failed
#20 157.5 make[1]: Leaving directory '/PI'
#20 157.5 make: *** [all] Error 2
#20 157.5 Makefile:384: recipe for target 'all' failed

```

not sure why these files are missing. 

In the long run I guess it would be beneficial to simplify and update the docker environment and the corresponding documentation as much as possible to make newbies' (like myself) lives easier. 
I'll try to help as much as I can, but as I said, I quite new to the topic and don't know C/C++ very well. But I'm familiar with Docker, so maybe that helps 😄 . 

Is there a reason why all three Docker files have different base images?

**Comment by antoninbas** [comment]
Sorry for the delay. It may be a good idea to just delete that Dockerfile actually, especially if it's broken :)
It predates the inclusion of simple_switch_grpc in the main bmv2 Docker image (p4lang/behavioral-model), and doesn't really serve a purpose anymore.

**Pull request closed without merging**
