### PR TITLE
change enqueue and dequeue qdepth to the size of related priority queue

### LINKED ISSUE #1258: Queue metadata with multiqueue
Hi! I am working with 3 priority queues on simple_switch, and I am trying to collect InBand Network Telemetry data, about the occupation of these queues. But when I am generating traffic in only one queue (for example queue 0), the enq_qdepth and deq_qdepth values of all three queues are getting high, while the other queues (1 and 2) are supposed to be empty.

I am also checking deq_timedelta, and in this case only in queue 0 I am getting high values (it is the correct behavior I think).

Other thing that I noticed is that when I am generating traffic in 2 queues, the queue depth values are getting higher than 64 (I set the size with set_queue_depth command)

So I have a question: the enq_qdepth and deq_qdepth metadata are about the number of packets adding all the queues in total? Or something is wrong here?

### PR DESCRIPTION
**Pull request by rizkyramadhana26**
Dear, All. This is my first attempt to contribute to the open source community. I propose a PR to fix p4lang/project-ideas#7 and fix #1258 

- I ran and passed the style check
`./tools/check_style.sh`
- I also built successfully using the same flag as the CI
`./configure --with-pdfixed --with-pi --with-stress-tests --enable-debugger --enable-Werror`
- Is it sufficient to use the other variant of size() to solve this issue?

Any input is much appreciated since it is my first time creating a PR for an open source software. Thank you!

### CODE REVIEW

**Comment by jafingerhut** [comment]
Welcome!

Take a look at the test results on this page: https://github.com/p4lang/behavioral-model/pull/1270

You will see one called "DCO" that failed.  There should be a "Details" link to the right of that (and in general for any test that failed).  There are instructions with `git` commands there that you can run in order to "sign" your commits, which basically just authorizes that you wrote them, not someone else.

**Comment by rizkyramadhana26** [comment]
I fixed that issue and I am sorry to populate the CI more than it is needed. Thanks!

**Comment by jafingerhut** [comment]
It seems reasonable to me to consider this a bug fix and not make a command line option for it.

That said, I am not actually opposed to a command line option if you think it may help.

**Comment by antoninbas** [comment]
Thanks @jafingerhut - sounds good to me, we can treat this as a bug fix and change the behavior unconditionally

**Comment by rizkyramadhana26** [comment]
Awesome. Should I add "Fixes #1258" only to the commit message? Or should I also add that to the PR's title or description?

**Comment by antoninbas** [comment]
> Awesome. Should I add "Fixes #1258" only to the commit message? Or should I also add that to the PR's title or description?

usually commit message + PR description is what I go for

**Comment by rizkyramadhana26** [comment]
I have mentioned related issues in the commit message and PR's description. All check are passed too. Thanks!

**Review by antoninbas — APPROVED** [review]

**Pull request merged**
