### PR TITLE
Remove warnings when compiling in GCC 5

### PR DESCRIPTION
**Pull request by ddompe**
Signed-off-by: Diego Dompe <dompe@hpe.com>

### CODE REVIEW

**Comment by antoninbas** [comment]
Hi Diego,
Please provide us with the version of gcc 5 you have been using.

**Comment by ddompe** [comment]
gcc 5.3

**Comment by antoninbas** [comment]
No compilation errors observed when compiling with `-O0` and the following gcc version:
`gcc version 5.3.0 20151204 (Ubuntu 5.3.0-3ubuntu1~14.04)`

**Comment by ddompe** [comment]
are you using -Wall -Werror ?

**Comment by antoninbas** [comment]
yes these are always used
I also tried with gcc 5.3.1 which is the default on Ubuntu 16.04:
`gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2)`

**Comment by vgurevich** [comment]
Hello Antonin,

GCC never complains about unused variables, unreachable statements and so
on  under -O0, because it doesn't perform the necessary flow analysis. You
should start seeing the warnings using -O2 and the like.

Thanks,
Vladimir

**Comment by antoninbas** [comment]
Nothing changed when I compiled with `O2` (gcc 5.3.0 and gcc 5.3.1)
I will add that the Travis regressions, which use gcc 4.8, clang 3.6 and gcc 5.x (I think x is 1, but I am unsure) and compile with `O2`, do not give any compilation errors.
I seem to remember that an old version of bmv2 was compiling with these warnings. However it was fixed quite a long time ago. Diego, did you observe this with a recent version of bmv2? If your version is up-to-date but you are still seeing these warnings, it would help to have the output of `g++ -v`, as well as the compiler output.

**Comment by ddompe** [comment]
Here is the compiler information:

`# x86_64-openswitch-linux-g++ -v       
Using built-in specs.
COLLECT_GCC=x86_64-openswitch-linux-g++
COLLECT_LTO_WRAPPER=/ws/ops-next3/build/tmp/sysroots/x86_64-linux/usr/bin/x86_64-openswitch-linux/../../libexec/x86_64-openswitch-linux/gcc/x86_64-openswitch-linux/5.3.0/lto-wrapper
Target: x86_64-openswitch-linux
Configured with: ../../../../../../work-shared/gcc-5.3.0-r0/gcc-5.3.0/configure --build=x86_64-linux --host=x86_64-linux --target=x86_64-openswitch-linux --prefix=/ws/ops-next/build/tmp/sysroots/x86_64-linux/usr --exec_prefix=/ws/ops-next/build/tmp/sysroots/x86_64-linux/usr --bindir=/ws/ops-next/build/tmp/sysroots/x86_64-linux/usr/bin/x86_64-openswitch-linux --sbindir=/ws/ops-next/build/tmp/sysroots/x86_64-linux/usr/bin/x86_64-openswitch-linux --libexecdir=/ws/ops-next/build/tmp/sysroots/x86_64-linux/usr/libexec/x86_64-openswitch-linux --datadir=/ws/ops-next/build/tmp/sysroots/x86_64-linux/usr/share --sysconfdir=/ws/ops-next/build/tmp/sysroots/x86_64-linux/etc --sharedstatedir=/ws/ops-next/build/tmp/sysroots/x86_64-linux/com --localstatedir=/ws/ops-next/build/tmp/sysroots/x86_64-linux/var --libdir=/ws/ops-next/build/tmp/sysroots/x86_64-linux/usr/lib/x86_64-openswitch-linux --includedir=/ws/ops-next/build/tmp/sysroots/x86_64-linux/usr/include --oldincludedir=/ws/ops-next/build/tmp/sysroots/x86_64-linux/usr/include --infodir=/ws/ops-next/build/tmp/sysroots/x86_64-linux/usr/share/info --mandir=/ws/ops-next/build/tmp/sysroots/x86_64-linux/usr/share/man --disable-silent-rules --disable-dependency-tracking --with-libtool-sysroot=/ws/ops-next/build/tmp/sysroots/x86_64-linux --enable-clocale=generic --with-gnu-ld --enable-shared --enable-languages=c,c++ --enable-threads=posix --disable-multilib --enable-c99 --enable-long-long --enable-symvers=gnu --enable-libstdcxx-pch --program-prefix=x86_64-openswitch-linux- --without-local-prefix --enable-lto --enable-libssp --enable-libitm --disable-bootstrap --disable-libmudflap --with-system-zlib --with-linker-hash-style=gnu --enable-linker-build-id --with-ppl=no --with-cloog=no --enable-checking=release --enable-cheaders=c_global --without-isl --with-gxx-include-dir=/not/exist/usr/include/c++/5.3.0 --with-sysroot=/not/exist --with-build-sysroot=/ws/ops-next/build/tmp/sysroots/appliance --enable-poison-system-directories --with-mpfr=/ws/ops-next/build/tmp/sysroots/x86_64-linux/usr --with-system-zlib --disable-static --disable-nls --enable-__cxa_atexit
Thread model: posix
gcc version 5.3.0 (GCC) 
`

Here is the failure log:

`x86_64-openswitch-linux-libtool: compile:  x86_64-openswitch-linux-g++ -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse --sysroot=/ws/ops-next3/build/tmp/sysroots/appliance -DHAVE_CONFIG_H -I. -I../.. -DBMELOG_ON -I../../modules/bf_lpm_trie/include -isystem../../third_party/jsoncpp/include -isystem../../third_party/spdlog/include -I../../modules/BMI/include -I./include/ -g -O1 -Wall -Werror -Wextra -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/ws/ops-next3/build/tmp/work/core2-64-openswitch-linux/ops-p4dp/gitAUTOINC+2c4a6cd0d4-r0_appliance=/usr/src/debug/ops-p4dp/gitAUTOINC+2c4a6cd0d4-r0_appliance -fdebug-prefix-map=/ws/ops-next3/build/tmp/sysroots/x86_64-linux= -fdebug-prefix-map=/ws/ops-next3/build/tmp/sysroots/appliance= -fvisibility-inlines-hidden -std=c++11 -c src/actions.cpp  -fPIC -DPIC -o src/.libs/actions.o
| In file included from src/calculations.cpp:26:0:
| src/calculations.cpp:68:15: error: 'bm::{anonymous}::xxh64_create_' defined but not used [-Werror=unused-variable]
|  REGISTER_HASH(xxh64);
|                ^
| ./include/bm_sim/calculations.h:400:8: note: in definition of macro 'REGISTER_HASH'
|    bool hash_name##_create_ =                                            \
|         ^
| src/calculations.cpp:88:15: error: 'bm::{anonymous}::crc16_create_' defined but not used [-Werror=unused-variable]
|  REGISTER_HASH(crc16);
|                ^
| ./include/bm_sim/calculations.h:400:8: note: in definition of macro 'REGISTER_HASH'
|    bool hash_name##_create_ =                                            \
|         ^
| src/calculations.cpp:102:15: error: 'bm::{anonymous}::crc32_create_' defined but not used [-Werror=unused-variable]
|  REGISTER_HASH(crc32);
|                ^
| ./include/bm_sim/calculations.h:400:8: note: in definition of macro 'REGISTER_HASH'
|    bool hash_name##_create_ =                                            \
|         ^
| src/calculations.cpp:116:15: error: 'bm::{anonymous}::crcCCITT_create_' defined but not used [-Werror=unused-variable]
|  REGISTER_HASH(crcCCITT);
|                ^
| ./include/bm_sim/calculations.h:400:8: note: in definition of macro 'REGISTER_HASH'
|    bool hash_name##_create_ =                                            \
|         ^
| src/calculations.cpp:164:15: error: 'bm::{anonymous}::cksum16_create_' defined but not used [-Werror=unused-variable]
|  REGISTER_HASH(cksum16);
|                ^
| ./include/bm_sim/calculations.h:400:8: note: in definition of macro 'REGISTER_HASH'
|    bool hash_name##_create_ =                                            \
|         ^
| src/calculations.cpp:172:15: error: 'bm::{anonymous}::csum16_create_' defined but not used [-Werror=unused-variable]
|  REGISTER_HASH(csum16);
|                ^
| ./include/bm_sim/calculations.h:400:8: note: in definition of macro 'REGISTER_HASH'
|    bool hash_name##_create_ =                                            \
|         ^
| src/calculations.cpp:185:15: error: 'bm::{anonymous}::identity_create_' defined but not used [-Werror=unused-variable]
|  REGISTER_HASH(identity);
|                ^
| ./include/bm_sim/calculations.h:400:8: note: in definition of macro 'REGISTER_HASH'
|    bool hash_name##_create_ =                                            \
|         ^
| cc1plus: all warnings being treated as errors
| make[3]: *** [src/calculations.lo] Error 1
| make[3]: *** Waiting for unfinished jobs....
| make[3]: Leaving directory `/ws/ops-next3/build/tmp/work/core2-64-openswitch-linux/ops-p4dp/gitAUTOINC+2c4a6cd0d4-r0_appliance/git/modules/bm_sim'
| make[2]: *** [all-recursive] Error 1
| make[2]: Leaving directory `/ws/ops-next3/build/tmp/work/core2-64-openswitch-linux/ops-p4dp/gitAUTOINC+2c4a6cd0d4-r0_appliance/git/modules'
| make[1]: *** [all-recursive] Error 1
| make[1]: Leaving directory `/ws/ops-next3/build/tmp/work/core2-64-openswitch-linux/ops-p4dp/gitAUTOINC+2c4a6cd0d4-r0_appliance/git'
| make: *** [all] Error 2
`

**Comment by antoninbas** [comment]
Hi Diego,
The logs confirmed to me that you are using an older version of bmv2.

**Comment by ddompe** [comment]
Yes, however this is the branch supported by OpenSwitch. How is it fixed on newer code?

**Comment by ddompe** [comment]
btw, the pull request goes agains the ops branch, so this branch in fact has the issue. Can you try to reproduce it using this branch?

**Comment by antoninbas** [comment]
@pbhide please cherry-pick 49c0508c123f6602222e85e7c7540100f34bcbe4 into the ops branch which will get rid of the warning

**Pull request closed without merging**
